### ISSUE TITLE
is comet cache dead ?

### ISSUE THREAD

**Issue by ionixxz** [websharks/zencache#942]
STOP REPLYING TO THIS IT ISNT RELATED TO MY ISSUE

**Comment by Reedyseth** [comment]
The projects haven't been updated in a few years. It is not compatible with the latest WordPress version anymore (6.4.1).

**Comment by ionixxz** [comment]
> The projects haven't been updated in a few years. It is not compatible with the latest WordPress version anymore (6.4.1).

Is there any updates for this software as its something I paid for and per the website shows its operational still

**Comment by Reedyseth** [comment]
You can log in to your dashboard account on their website. Maybe they built a new version that is not hosted here.

**Comment by orlandoayeras** [comment]
Hey guys. This has been a problem for our customer who uses the Comet Cache Pro plugin. We updated to WP 6.4.1 and due to this, we are encountering wild permission errors:
`Warning: rename(/code/wp-content/cache/comet-cache/cache,/code/wp-content/cache/comet-cache/cache-657b1b8053ffe248625836-tmp): Input/output error in /code/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php on line 157 Fatal error: Uncaught Exception: Unable to delete files. Rename failure on directory: `/code/wp-content/cache/comet-cache/cache`. in /code/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php:158 Stack trace: #0 /code/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php(286): WebSharks\CometCache\Pro\Classes\AbsBaseAp->deleteFilesFromCacheDir('/^https?\\/[^\\/]...', false) #1 /code/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php(61): WebSharks\CometCache\Pro\Classes\AbsBaseAp->deleteFilesFromHostCacheDir('/^https?\\/[^\\/]...') #2 /code/wp-content/plugins/comet-cache-pro/src/includes/traits/Plugin/WcpPostUtils.php(90): WebSharks\CometCache\Pro\Classes\AbsBaseAp->clearFilesFromHostCacheDir('/^\\/news\\/weath...') #3 /code/wp-includes/class-wp-hook.php(312): WebSharks\CometCache\Pro\Classes\Plugin->autoClearPostCache(13965) #4 /code/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters('', Array) #5 /code/wp-includes/plugin.php(517): in /code/wp-content/plugins/comet-cache-pro/src/includes/traits/Shared/CacheDirUtils.php on line 158`

We already reverted to 6.3.2 but still encountering the issue. Is anyone familiar with how to get this gone?

**Comment by Reedyseth** [comment]
@orlandoayeras I will suggest without touching code the following:

1. Deactivate the Comment Cache plugin.
2. Delete the folder under `/code/wp-content/cache/comet-cache/cache` with [S]FTP or login to your server with SSH.
3. Activate the plugin again.

**Comment by theperfectwill** [comment]
@orlandoayeras 

I have been working on Comet Cache Pro, as a rebuild, with the knowledge of the previous developer(s). I'd recommend you stop using it in its current state. Even if you get rid of that error, there are other errors, and if you update to PHP 8.2, you will likely encounter a Fatal Error if I remember correctly. Comet Cache hasn't been updated in years, and has outdated code and libraries, and while still available from the site, is essentially (I would consider) abandoned (in terms of updates).
